import type { Metadata } from 'next';
import '@/style/globals.css';

export const metadata: Metadata = {
  title: '메인 페이지',
  description: 'Generated by create next app',
};

export default function MainPageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
