import Header from '@/components/domains/landing/header/Header';
import { Metadata } from 'next';
import '@/style/globals.css';

export const metadata: Metadata = {
  title: '메인 페이지',
  description: 'Generated by create next app',
};

export default function MainPageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full h-screen flex flex-col gap-10 mx-auto">
      <Header />
      {children}
    </div>
  );
}
