import type { Metadata } from 'next';
import '@/style/globals.css';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import Header from '@/components/domains/landing/header/Header';

export const metadata: Metadata = {
  title: {
    template: 'Calog | %s',
    default: 'Calog',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="ko">
      <body>
        <Header session={session} />
        <div id="modal" />
        <div className="w-full h-screen flex flex-col gap-10 mx-auto">{children}</div>
      </body>
    </html>
  );
}
