name: deploy to S3

on:
  push:
    branches:
      - dev

env:
  S3_BUCKET_NAME: calog-client-build
  CODE_DEPLOY_APPLICATION_NAME: calog-client-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: group1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Make zip file
        run: |
          # 1. 정적 파일 복사 (public 폴더)
          cp -r public .next/standalone/public
          
          # 2. Next.js 필수 리소스 복사 (.next/static)
          mkdir -p .next/standalone/.next
          cp -r .next/static .next/standalone/.next/static
          
          # 3. 배포 스크립트 및 설정 복사
          cp appspec.yml .next/standalone/appspec.yml
          cp -r scripts .next/standalone/scripts
          
          # 4. 압축 실행 (standalone 내부)
          cd .next/standalone
          zip -qq -r ../../calog.zip .

      # Github Action에서 AWS의 권한 자격을 얻어오는 단계
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 압축된 파일을 S3에 업로드
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./calog.zip s3://$S3_BUCKET_NAME/calog.zip

      # S3에 업로드 된 빌드 파일을 이용해 CodeDeploy가 정의된 동작을 하도록 트리거
      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=calog.zip
